project:
  type: website
  output-dir: _site

website:
  title: "Sitio Julio Vargas"
  navbar:
    left:
      - href: assignment03-juliovargas.qmd
        text: Inicio

format:
  html:
    theme: cosmo
